-- This statement will succeed
CREATE TABLE XTABLE_A (
	NAME VARCHAR(40) NOT NULL,
	CONSTRAINT PK_TABLE_A PRIMARY KEY(NAME)
);

-- This statement will fail
CREATE TABLE XTABLE_B (
	NAME VARCHA(40) NOT NULL,
	CONSTRAINT PK_TABLE_B PRIMARY KEY(NAME)
);

-- @Rollback
DROP TABLE IF EXISTS XTABLE_B;
DROP TABLE IF EXISTS XTABLE_A;
